service: serverless-authorizer

provider: aws

functions:
  profile:
    handler: index.profile
    events:
      - http:
          path: profile
          method: get
          authorizer:
            name: auth
            resultTtlInSeconds: 300
            type: request
  auth:
    handler: index.auth

